name: Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run-tests:
    name: Run pytest suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: pytest -q
